---
- hosts: rh3
  become: true
  tasks:


  - name: take care of firewall
    firewalld:
      service: dns
      immediate: true
      state: enabled
      permanent: true

  - name: install dns
    yum:
      name: bind
      state: installed

  - name: copy over the required setup files
    copy:
      src: /home/devops/RH358/files/named.conf.template
      dest: /etc/named.conf
      group: named
      mode: '0640'
      setype: named_conf_t
    notify: restart named

  - name: add required zone file
    template:
      src: /home/devops/RH358/files/named.home.local.template
      dest: /var/named/named.home.local
      group: named
      mode: '0640'
      setype: named_zone_t
    notify: restart named

  - name: add required zone file
    template:
      src: /home/devops/RH358/files/named.home.reverse.template
      dest: /var/named/named.reverse.local
      group: named
      mode: '0640'
      setype: named_zone_t
    notify: restart named



  handlers:
  
  - name: restart named
    service:
      name: named
      state: restarted
      enabled: true
